#!/usr/bin/env python3
"""Bootstrap local dependencies and write the Lightroom plugin config file."""

from __future__ import annotations

import argparse
import platform
import shutil
import subprocess
from pathlib import Path


REQUIRED_BREW_FORMULAS = {
    "uv": "uv",
    "dnglab": "dnglab",
    "exiftool": "exiftool",
}


def parse_args() -> argparse.Namespace:
    repo_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        default=str(repo_root / "lightroom-flatfield.lrplugin" / "ffcplugin.config"),
        help="Config file to write. Default: lightroom-flatfield.lrplugin/ffcplugin.config",
    )
    parser.add_argument("--python", dest="python_command", help="Python executable to store in the config.")
    parser.add_argument("--backend", default="auto", choices=("auto", "numpy", "numexpr"))
    parser.add_argument("--compressor", default="auto", choices=("auto", "dnglab", "adobe", "none"))
    parser.add_argument(
        "--compression",
        default="auto",
        choices=("auto", "none", "lossless-jpeg", "lossless-jxl"),
    )
    parser.add_argument("--smooth-sigma", default="192")
    parser.add_argument("--norm-percentile", default="70")
    parser.add_argument("--dust-sigma", default="32")
    parser.add_argument("--dust-threshold", default="0.02")
    parser.add_argument("--dust-amount", default="1.0")
    parser.add_argument("--dust-max-gain", default="1.10")
    parser.add_argument("--output-subfolder", default="flatfield-corrected")
    parser.add_argument("--no-install", action="store_true", help="Do not install missing Homebrew packages.")
    parser.add_argument("--skip-uv-sync", action="store_true", help="Do not run uv sync.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    repo_root = Path(__file__).resolve().parents[1]
    ensure_tools(args.no_install)
    uv = find_executable("uv")
    if uv is None:
        raise SystemExit("uv is required but was not found.")

    if not args.skip_uv_sync:
        run([str(uv), "sync", "--extra", "dev"], cwd=repo_root)

    python_command = Path(args.python_command).expanduser() if args.python_command else repo_root / ".venv" / bin_dir() / python_name()
    if not python_command.exists():
        raise SystemExit(f"Configured Python does not exist: {python_command}")

    config = {
        "pythonCommand": python_command.absolute(),
        "helperScriptPath": repo_root / "scripts" / "stage_calibration.py",
        "applyScriptPath": repo_root / "scripts" / "run_ffc_apply.py",
        "exiftoolPath": find_executable("exiftool"),
        "outputSubfolder": args.output_subfolder,
        "backend": args.backend,
        "compressor": args.compressor,
        "compression": args.compression,
        "smoothSigma": args.smooth_sigma,
        "normPercentile": args.norm_percentile,
        "dustSigma": args.dust_sigma,
        "dustThreshold": args.dust_threshold,
        "dustAmount": args.dust_amount,
        "dustMaxGain": args.dust_max_gain,
        "dnglabPath": find_executable("dnglab"),
        "dngConverterPath": find_adobe_dng_converter(),
    }

    output = Path(args.output).expanduser()
    write_config(output, config)
    print(f"Wrote Lightroom plugin config: {output}")
    print(f"Python: {python_command}")
    return 0


def ensure_tools(no_install: bool) -> None:
    missing = [name for name in REQUIRED_BREW_FORMULAS if find_executable(name) is None]
    if not missing:
        return

    if no_install:
        raise SystemExit(f"Missing required command(s): {', '.join(missing)}")

    brew = find_executable("brew")
    if brew is None:
        raise SystemExit(
            "Missing required command(s): "
            + ", ".join(missing)
            + ". Install Homebrew from https://brew.sh, then rerun this script."
        )

    formulas = [REQUIRED_BREW_FORMULAS[name] for name in missing]
    run([str(brew), "install", *formulas])


def write_config(path: Path, values: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by scripts/init_lightroom_config.py.",
        "# Regenerate this file after moving the repo or rebuilding the venv.",
        "",
    ]
    for key, value in values.items():
        if value is None:
            value = ""
        lines.append(f"{key}={quote_value(str(value))}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def quote_value(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def find_executable(name: str) -> Path | None:
    found = shutil.which(name)
    candidates = []
    if found:
        candidates.append(Path(found))
    candidates.extend(
        [
            Path("/opt/homebrew/bin") / name,
            Path("/usr/local/bin") / name,
            Path.home() / ".local" / "bin" / name,
        ]
    )
    for candidate in candidates:
        if candidate.exists():
            return candidate.absolute()
    return None


def find_adobe_dng_converter() -> Path | None:
    names = ["Adobe DNG Converter"]
    if platform.system() == "Windows":
        names.append("Adobe DNG Converter.exe")
    for name in names:
        found = shutil.which(name)
        if found:
            return Path(found).absolute()

    candidates = [
        Path("/Applications/Adobe DNG Converter.app"),
        Path("/Applications/Adobe DNG Converter.app/Contents/MacOS/Adobe DNG Converter"),
        Path(r"C:\Program Files\Adobe\Adobe DNG Converter\Adobe DNG Converter.exe"),
        Path(r"C:\Program Files\Adobe DNG Converter.exe"),
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return None


def bin_dir() -> str:
    return "Scripts" if platform.system() == "Windows" else "bin"


def python_name() -> str:
    return "python.exe" if platform.system() == "Windows" else "python"


def run(cmd: list[str], *, cwd: Path | None = None) -> None:
    print("+ " + " ".join(cmd))
    subprocess.run(cmd, cwd=cwd, check=True)


if __name__ == "__main__":
    raise SystemExit(main())
